---
# Source: frontend-demo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-demo
  labels:
    helm.sh/chart: frontend-demo-0.1.0
    app.kubernetes.io/name: frontend-demo
    app.kubernetes.io/instance: frontend-demo
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-demo
      app.kubernetes.io/instance: frontend-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-demo
        app.kubernetes.io/instance: frontend-demo
    spec:
      serviceAccountName: frontend-demo
      securityContext:
        {}
      containers:
        - name: frontend-demo
          securityContext:
            {}
          image: "nginx:1.0.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: BACKEND_DEMO_URL
              value: ""
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:80/actuator/health
          readinessProbe:
            exec:
              command:
                - curl
                - localhost:80/actuator/health
          resources:
            {}
