---
# Source: frontend-demo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-demo
  labels:
    helm.sh/chart: frontend-demo-0.1.0
    app.kubernetes.io/name: frontend-demo
    app.kubernetes.io/instance: frontend-demo
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
