---
# Source: frontend-demo/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-demo
  labels:
    helm.sh/chart: frontend-demo-0.1.0
    app.kubernetes.io/name: frontend-demo
    app.kubernetes.io/instance: frontend-demo
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: frontend-demo
    app.kubernetes.io/instance: frontend-demo
